################################################################
###### Example PBS (Portable Batch System) Script
#################################################################
#! /bin/bash -l
#
### Name the job
#PBS -N lattice
#
### Set the number of nodes and cores to use for the job
#PBS -l nodes=1:ppn=12
#
### Type of job to run
#PBS -q generic
#
### Path to start this script from
#PBS -d /home6/zsailer/ensembles-final/pop-1
#
### Path to output file
#PBS -o /home6/zsailer/ensembles-final/pop-1/output.txt
#
#
### Combine the output and error file
#PBS -j oe
#
### Email me when the job is done
#PBS -m abe
#PBS -M zsailer@uoregon.edu
#
##################################################################
###### Write program to run here
##################################################################

POPSIZE=1
N_MOVES=7
N_BRANCHES=3
N_STATES=3

nohup python main.py 72 MIMKCDLVKYDW --db URULLDDDRRU UURDDDLLUUU UUURRDDDLUU --target URULLDDDRRU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 73 PMDMFMMFYDHP --db UURDDRUURDD UURDDRUUULL UUURRDLDDRU --target UURDDRUURDD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 74 MIKPKVWEFMLH --db URDDLLLURUL URRDLDLDRRU UUURDDDRUUU --target URDDLLLURUL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 75 HCFWKFVKADCI --db URDRUUULLDR UUURRDDDLUU UURRRDDLLUR --target URDRUUULLDR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 76 CWEVMCLDMKIF --db UURDDRRUULD URULURRDDDL URDRUUULLDR --target UURDDRRUULD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 77 AFFMIPWRPCKI --db URULURRDDDL URRDLDRDLLU UUURRDLDRDL --target URULURRDDDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 78 AIFEWKWFDIFM --db UUURRDDDLUU URDRUUULLDR URDRUULLLDD --target UUURRDDDLUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 79 YMDLHFIHYKME --db UURRDLDRRUU URULURRDDDL UURRDLDRDLL --target UURRDLDRRUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 80 PCNLWFFYMGVP --db UURRDLDRRUU URDDLLLURUL UURRDLDRDLL --target UURRDLDRRUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 81 MFMKVDCCKYKW --db URULLDDDRRU URDRUULLLDD UURDDDLLUUU --target URULLDDDRRU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 82 MSFKFFFPSQEH --db URRDLDLDRRU URRDLDRDLLU UURDDDLLUUU --target URRDLDLDRRU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 83 HCWKMMFYQCWG --db UUURDDDRUUU UURRRDDLULD UURRDLDRRUU --target UUURDDDRUUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
