################################################################
###### Example PBS (Portable Batch System) Script
#################################################################
#! /bin/bash -l
#
### Name the job
#PBS -N lattice
#
### Set the number of nodes and cores to use for the job
#PBS -l nodes=1:ppn=12
#
### Type of job to run
#PBS -q generic
#
### Path to start this script from
#PBS -d /home6/zsailer/ensembles-final/pop-1
#
### Path to output file
#PBS -o /home6/zsailer/ensembles-final/pop-1/output.txt
#
#
### Combine the output and error file
#PBS -j oe
#
### Email me when the job is done
#PBS -m abe
#PBS -M zsailer@uoregon.edu
#
##################################################################
###### Write program to run here
##################################################################

POPSIZE=1
N_MOVES=7
N_BRANCHES=3
N_STATES=3

nohup python main.py 84 HKWFCYDCDFVM --db URDDLDRRUUU URDRURDDLLL URDDLLLURUL --target URDDLDRRUUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 85 MKVKCFCCPCKW --db URRDLDRDLLU URRDLDLDRRU UURDDRRULUR --target URRDLDRDLLU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 86 CFDWAKWIMFLH --db UURRRDLLDRR UURRDLDRDLL URDDLLUULDD --target UURRRDLLDRR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 87 WYLKLDCIMCDM --db UUURRDLDRDL UUURRDLDDRU URDRUULLURR --target UUURRDLDRDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 88 LKADHIFDQVDM --db URRDLDRDLLU URRDLDLDRRU UUURDDDRUUU --target URRDLDRDLLU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 89 AFFEYKCWKIMF --db UUURRDDDLUU URRDDDLLURU URULLDDDRRU --target UUURRDDDLUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 90 AWQFMVIEWMCQ --db UURDDRRULUR URDDLDRRUUU UURDDRRUULD --target UURDDRRULUR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 91 PWQWASAKYYMI --db UURRRDDLLUR UUURRDDDLUU UURRRDDLULD --target UURRRDDLLUR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 92 CKMLKVNMIFWC --db URRRDDLULDL UURRDLDRDLL UURRDLDRRUU --target URRRDDLULDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 93 CFFMLKWQWWDC --db URULURRDDDL URDRUUULDLU UURDDRRULUR --target URULURRDDDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 94 MCKPKYLDLDCF --db URDDLLLUURD URDRUUULLDR UURRRDDLLUR --target URDDLLLUURD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 95 CVKAKIIFMDHH --db UURRDLDRDLL URDRUULLLDD URDRUULLURR --target UURRDLDRDLL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
