################################################################
###### Example PBS (Portable Batch System) Script
#################################################################
#! /bin/bash -l
#
### Name the job
#PBS -N lattice
#
### Set the number of nodes and cores to use for the job
#PBS -l nodes=1:ppn=12
#
### Type of job to run
#PBS -q generic
#
### Path to start this script from
#PBS -d /home6/zsailer/ensembles-final/pop-1
#
### Path to output file
#PBS -o /home6/zsailer/ensembles-final/pop-1/output.txt
#
#
### Combine the output and error file
#PBS -j oe
#
### Email me when the job is done
#PBS -m abe
#PBS -M zsailer@uoregon.edu
#
##################################################################
###### Write program to run here
##################################################################

POPSIZE=1
N_MOVES=7
N_BRANCHES=3
N_STATES=3

nohup python main.py 48 PLCQYFFMKFCP --db UUURDDDRUUU UURDDDLLUUU UURRDLDRRUU --target UUURDDDRUUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 49 AISCFLMKWFCR --db UURDDRRULUR URRRDDLULDL URDDLLLURUL --target UURDDRRULUR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 50 MMIEWEWWDVDF --db URULLDDDRRU UUURRDLDRDL UUURRDLDDRU --target URULLDDDRRU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 51 VFMMMKVDWVSL --db URULURRDDDL UUURRDLDDRU UUURRDLDRDL --target URULURRDDDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 52 PMDMMFWMCKHE --db UURRDLDRRUU UURDRURDDLL URULURRDDDL --target UURRDLDRRUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 53 MLNPDWFDIFFA --db URDDLLLURUL URDRUUULDLU UURRRDDLULD --target URDDLLLURUL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 54 IQCFCCKHKCMM --db URDRURDDLLL URRRDDLULDL URDRUUULDLU --target URDRURDDLLL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 55 AIKWYQYMMIWH --db UURRRDLLDRR UURRDLDRDLL UUURRDDDLUU --target UURRRDLLDRR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 56 WQHDHFFYKVQM --db URRDLDRDLLU URRDLDLDRRU UURRDLDRDLL --target URRDLDRDLLU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 57 PILSHDVWKMMF --db UUURRDDDLUU URDRUULLLDD URDRUULLURR --target UUURRDDDLUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 58 ICDVKLLKSKCI --db URDDLLLUURD UURDDDLLUUU URRDDDLLURU --target URDDLLLUURD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 59 FMINWWDIEFWA --db UURDDDLLUUU URULLDDDRRU URDDLLUUURR --target UURDDDLLUUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
