################################################################
###### Example PBS (Portable Batch System) Script
#################################################################
#! /bin/bash -l
#
### Name the job
#PBS -N lattice
#
### Set the number of nodes and cores to use for the job
#PBS -l nodes=1:ppn=12
#
### Type of job to run
#PBS -q generic
#
### Path to start this script from
#PBS -d /home6/zsailer/ensembles-final/pop-1
#
### Path to output file
#PBS -o /home6/zsailer/ensembles-final/pop-1/output.txt
#
#
### Combine the output and error file
#PBS -j oe
#
### Email me when the job is done
#PBS -m abe
#PBS -M zsailer@uoregon.edu
#
##################################################################
###### Write program to run here
##################################################################

POPSIZE=1
N_MOVES=7
N_BRANCHES=3
N_STATES=3

nohup python main.py 0 HDHNWFFYDVKM --db URRDLDLDRRU URRDLDRDLLU URDRUUULDLU --target URRDLDLDRRU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 1 FCKRKCIKVKCM --db URDDLLLUURD UURRDLDRDLL URDDLLLURUL --target URDDLLLUURD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 2 PVKFIMIKYLCR --db UURDDRRULUR UURDRURDDLL UURRDLDRRUU --target UURDDRRULUR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 3 RLKVYCIECKCR --db UURRDLDRRUU UURRDLDRDLL URULURRDDDL --target UURRDLDRRUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 4 CMFCDVIKIMWT --db URDRUUULDLU URRRDDLULDL URULURRDDDL --target URDRUUULDLU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 5 AVMIQWWMIKWH --db URDRUULLURR UURRDLDRDLL URDDLDRRUUU --target URDRUULLURR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 6 CCIKMEMIFWKC --db UUURRDLDRDL UUURDDDRUUU UURRRDLLDRR --target UUURRDLDRDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 7 MCKPQWIICNLA --db URDDLLUULDD UURDDDLLUUU URDDLDRRUUU --target URDDLLUULDD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 8 HHFWKMIMFKWA --db URDRUULLURR URDDLLUULDD URDDLLUUURR --target URDRUULLURR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 9 PFFFCQHKHMKM --db URULURRDDDL URDRUULLLDD URDRUUULLDR --target URULURRDDDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 10 AWKIMIWFAKHH --db UURDDRUURDD UURRDLDRDLL UURDDRUUULL --target UURDDRUURDD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 11 FIKHKLMKWKLF --db URDDLLLUURD UURRRDDLLUR URDDLLUUURR --target URDDLLLUURD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
