################################################################
###### Example PBS (Portable Batch System) Script
#################################################################
#! /bin/bash -l
#
### Name the job
#PBS -N lattice
#
### Set the number of nodes and cores to use for the job
#PBS -l nodes=1:ppn=12
#
### Type of job to run
#PBS -q generic
#
### Path to start this script from
#PBS -d /home6/zsailer/ensembles-final/pop-1
#
### Path to output file
#PBS -o /home6/zsailer/ensembles-final/pop-1/output.txt
#
#
### Combine the output and error file
#PBS -j oe
#
### Email me when the job is done
#PBS -m abe
#PBS -M zsailer@uoregon.edu
#
##################################################################
###### Write program to run here
##################################################################

POPSIZE=1
N_MOVES=7
N_BRANCHES=3
N_STATES=3

nohup python main.py 24 PWLDHECWKMMF --db UUURRDDDLUU UURRRDDLULD UURRRDDLLUR --target UUURRDDDLUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 25 PITLLWCKWFCP --db UURDDRRULUR UURRRDDLULD UUURRDLDRDL --target UURDDRRULUR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 26 WMMQHSCFFCQM --db UUURRDLDRDL URDRUUULLDR URDRUULLURR --target UUURRDLDRDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 27 MMWDHKYFFHQW --db UUURRDLDRDL UUURRDLDDRU URRDDDLLURU --target UUURRDLDRDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 28 FKCKMIKAKMIF --db URRDDDLLURU UUURRDDDLUU UUURRDLDDRU --target URRDDDLLURU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 29 FCGEKHVRMICP --db URDDLLLURUL URDDLLUUURR URDDLLLUURD --target URDDLLLURUL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 30 WFFFFNCKMIKM --db URULURRDDDL URRRDDLULDL URDRUUULDLU --target URULURRDDDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 31 RCWICWRCCRVA --db UURDDRUUULL UURDDRUURDD UURRRDLLDRR --target UURDDRUUULL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 32 AFDVHKHFFIVY --db UURRRDLLDRR URDRUULLLDD URDRUULLURR --target UURRRDLLDRR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 33 FIKWKMLECGLF --db URDDLLLUURD URULLDDDRRU UUURRDDDLUU --target URDDLLLUURD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 34 RWLNWFMWKIIA --db UUURDDDRUUU UURDRURDDLL UURRDLDRRUU --target UUURDDDRUUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 35 WMIFWNHEVISM --db URULURRDDDL URRRDDLULDL URDRUUULLDR --target URULURRDDDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
