################################################################
###### Example PBS (Portable Batch System) Script
#################################################################
#! /bin/bash -l
#
### Name the job
#PBS -N lattice
#
### Set the number of nodes and cores to use for the job
#PBS -l nodes=1:ppn=12
#
### Type of job to run
#PBS -q generic
#
### Path to start this script from
#PBS -d /home6/zsailer/ensembles-final/pop-1
#
### Path to output file
#PBS -o /home6/zsailer/ensembles-final/pop-1/output.txt
#
#
### Combine the output and error file
#PBS -j oe
#
### Email me when the job is done
#PBS -m abe
#PBS -M zsailer@uoregon.edu
#
##################################################################
###### Write program to run here
##################################################################

POPSIZE=1
N_MOVES=7
N_BRANCHES=3
N_STATES=3

nohup python main.py 60 ITHFCMECECLY --db URDDLDRRUUU URDRURDDLLL URULURRDDDL --target URDDLDRRUUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 61 KCFRVKDIIRKE --db UUURRDLDRDL UUURRDLDDRU UURDDRUUULL --target UUURRDLDRDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 62 ACRCFIMDWFIR --db UURDDRRULUR UURDDDLLUUU UURDRURDDLL --target UURDDRRULUR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 63 PLKLAKLKCYFF --db UURRRDDLLUR URULURRDDDL URDDLLLUURD --target UURRRDDLLUR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 64 MFHWEPNPLDFH --db URDDLLUUURR URDDLLUULDD UURDDDLLUUU --target URDDLLUUURR --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 65 MKYEHFFHKCGM --db URRDLDRDLLU URRDLDLDRRU UURDRURDDLL --target URRDLDRDLLU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 66 GLMKWFFCKLMP --db UUURDDDRUUU URRRDDLULDL UURRDLDRRUU --target UUURDDDRUUU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 67 HKHKWFFIKVKM --db URRDLDLDRRU URRDLDRDLLU URDRUUULDLU --target URRDLDLDRRU --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 68 AWKIIFYRHKHI --db UURDRURDDLL URRDLDLDRRU URRDLDRDLLU --target UURDRURDDLL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 69 MMKWEFCFIPMC --db URDDLLUULDD UUURRDDDLUU URDDLLUUURR --target URDDLLUULDD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 70 FWKHKCIQLQMF --db URDDLLLUURD UURRRDDLLUR UURRRDDLULD --target URDDLLLUURD --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
nohup python main.py 71 WCMFCDYKLWKW --db URULURRDDDL URULLDDDRRU UURDDRUUULL --target URULURRDDDL --popsize $POPSIZE --n_moves $N_MOVES --n_branches $N_BRANCHES --n_states $N_STATES &
